- publicscript/Usacloud
Usacloudスタートアップスクリプトに対し`bash-completion`パッケージのインストール処理を追加します。  
これにより、bash + usacloudコマンドにてTABキーでの入力補完機能が利用可能となります。
> Usacloudへbash-completionパッケージ追加

- README.md
- publicscript/initial-setup.sh
CentOS 6.x/7.xの初期設定をするスクリプトを追加いたしました 🙏 
行う設定は、以下のとおりです。
* パッケージの最新化
* 新規ユーザの作成
* suコマンドの制限
* suコマンドの実行可能ユーザ・グループを限定する
* パスワード入力なしでsudoコマンドを利用可能にする
* ssh接続の制限
* rootユーザのsshログインを禁止する
* 公開鍵認証のみ接続を許可する（パスワード認証を禁止）
> CentOSの初期設定スクリプトを追加

- publicscript/mattermost.sh
チャットサーバの Mattermost Team Edition をインストールします。
アプリケーションバージョン
Mattermost: 3.10
Mysql: 5.7
事前作業として以下の2つが必要となります
1. さくらのクラウドDNSにゾーン登録を完了していること
2. さくらのクラウドAPIのアクセストークンを取得していること
スタートアップスクリプトの処理
1. パッケージのアップデートと必要なパッケージのインストール
2. さくらのクラウドDNSにA,MX,TXTレコード(SPF)の登録
3. Mysql 5.7 のインストールと設定
4. Mattermost 3.10.0 のインストールと設定
5. nginx の設定
6. postfix の設定
7. firewalld で 25/tcp,80/tcp,443/tcp をそれぞれオープン
8. certbotのインストールと証明書取得
9. メッセージの全文検索に対応する為に、ngramでインデックスを再作成
10. DNSに逆引きの登録
セットアップ後のアクセスURL(HTTPをhTTPSへリダイレクト)
http(s)://ドメイン
入力するDNSゾーンとドメイン
Zone Apex でドメインを登録したい場合は、ゾーンだけ入力し、ドメイン欄を入力しないこと
ドメインの A,MX,TXT レコードを新規登録します。既に登録されている場合はエラーになります
他
Mattermostの検索は２文字以上入力しないとマッチしない
> Mattermost add 20170713

- README.md
- publicscript/minio.sh
`ufw` コマンドを使うことから、現時点で対応しているパブリックアーカイブは `Ubuntu 16.04` のみです。
そのため、説明文とスタートアップスクリプトで OS 制限を追加しました。
> minioスクリプトで、Ubuntu 16.04の制限を追加

- publicscript/minio.sh
minio のスタートアップスクリプト中で、未使用フォームおよび変数がありました。
本スクリプトでは不要項目のため、削除しました。
> 未使用フォームの削除

- publicscript/zabbix-agent.sh
- publicscript/zabbix-agent_spec.rb
- publicscript/zabbix-server.sh
- publicscript/zabbix-server_spec.rb
インストールバージョンのデフォルトを 3.2 から 3.4 へ変更
スタートアップスクリプト実施後のテストに使用する spec ファイルの追加
> Zabbix Version 3.4 への対応

- publicscript/crowi/crowi.env
- publicscript/crowi/crowi.sh
- publicscript/crowi/crowi_spec.rb
さくらのクラウドDNSとLets Encrypt を使用したHTTPS対応処理追加
- APIキーを選択しないと IPアドレス:80 でのセットアップとなる
spec ファイルの追加(スタートアップスクリプトのテスト処理で使用)
env ファイルの追加(スタートアップスクリプトのテスト処理で使用)
> crowi スタートアップスクリプトのSSL対応

- publicscript/owncloud/owncloud.sh
2017/09/20現在公開されているスタートアップスクリプトを利用してowncloudサーバの構築を試みたところ、スクリプトの実行が失敗しておりました。
原因を調査してみたところ、スクリプトが参照しているowncloudのリポジトリが利用不能となっているようでした。
そこで、公式サイトを見ながら最新版のowncloudをインストールできるようにしてみました。
PHPは5.6にしないと怒られたので5.6で入れており、それに付随して必要なソフトウェアもインストールし、説明部分も補足しました。
折角なのでCentOS7版も作り、まとめました。
> owncloud 10 対応 & CentOS7 対応

- publicscript/usacloud/usacloud.sh
Usacloudの配布サイトのURL変更への対応を行いました。
- 旧: `https://usacloud.b.sakurastorage.jp/repos/setup-yum.sh`
- 新: `http://releases.usacloud.jp/usacloud/repos/setup-yum.sh`
> Usacloud 配布サイトURLの変更対応

- publicscript/terraform_for_sacloud/terraform_for_sacloud.sh
Terraform for さくらのクラウドの配布サイトのURL変更への対応を行いました。
- 旧: `https://terraform.b.sakurastorage.jp/downloads/`
- 新: `http://releases.usacloud.jp/terraform/`
> Terraform for さくらのクラウド 配布サイトのURL変更対応

- publicscript/drupal_for_centos7/drupal_for_centos7.sh
Drupalセットアップ時に必要となるRemiリポジトリを、スクリプト内でセットアップするよう明示しまいた。
> Drupal for CentOS7 - Remiリポジトリの利用を明示

- publicscript/terraform_for_sacloud/terraform_for_sacloud.sh
Terraform for さくらのクラウドのダウンロードURL誤りの修正を行っています。
> Terraform for さくらのクラウド ダウンロードURL修正

- publicscript/shirasagi/shirasagi.sh
インストール用スクリプトが、デフォルトでポート80を公開するようになった対応
- デフォルトのポートが 3000 から 80 に変更
- firewall-cmd もスクリプト側で対処しているので、スタートアップスクリプト側からは削除
> #72 Shirasagiインストールスクリプトの更新に伴い、ポート番号変更に対応

- publicscript/wordpress_for_kusanagi8/wordpress_for_kusanagi8.sh
kusanagi initコマンド実行時において、8.1.0から--ruby24、8.2.0から--dbsystem [mariadb|psql]のパラメータ指定が増えたので追加いたしました。
> KUSANAGI v8.1.0以降のパラメータ指定対応

- publicscript/wordpress_for_kusanagi8/wordpress_for_kusanagi8.sh
maxlen、minlen が存在する場合、 ex での指定がなくてもデフォルトの挙動として文字数の範囲が表示されるため
> ex で文字数の範囲を指定している箇所を削除

- publicscript/mastodon/mastodon.sh
mastodon の 2.5.0 で必要な node のバージョンに変更があった為、対応しました。
> node のバージョンを 6 から 8 に変更しました。

- publicscript/gitlab/gitlab.sh
runsvdir-start.service の起動から処理が進まない現象を確認したため、スクリプトを修正しました。
恐らく runsvdir-start.service ファイルで After=multi-user.target が指定されるようになった為だと思われます。
> スタートアップスクリプトが完了しない問題を対応しました。

- publicscript/rancher2-server/rancher.sh
- publicscript/rancher_for_sacloud/rancher_for_sacloud.sh
Kubernetesクラスタを管理できるOSS [Rancher](https://rancher.com)をインストールするスクリプトです。
- 対象OSはCentOS7
- Dockerをインストールし、Dockerを用いてRancherサーバをインストール
- Rancherサーバの管理者パスワードを指定可能
- Rancherサーバにさくらのクラウド向けノードドライバーを登録
- サーバ作成時にさくらのクラウドAPIキーを指定することでRancherのノードテンプレートを自動登録
サーバ作成後にブラウザで `https://<サーバのIPアドレス>`を開くことでRancherのコントロールパネルが利用可能です。Rancherにはさくらのクラウド向けの設定(ノードドライバー/ノードテンプレート)が指定済みとなっているため、すぐにさくらのクラウド上にKubernetesクラスタを作成することが可能です。
> Rancher 2.xサーバ構築スクリプト

- publicscript/rancher2_setup/rancher2_setup.sh
yumでDockerをインストールすると`docker exec`でエラーが発生するようになっています。
参考: https://bugzilla.redhat.com/show_bug.cgi?id=1655214
このため、暫定的にdockerをダウングレードする処理を追加しました。
> Rancher2セットアップ: 'docker exec'エラー回避のためdockerをダウングレード

- publicscript/rancher2_setup/rancher2_setup.sh
#123 の原因となった`docker exec`が実行できない問題に対応する更新版RPMパッケージがリリースされています。
参考: https://access.redhat.com/errata/RHBA-2018:3796
既にCentOSで利用できるようになっているため、ダウングレード処理を除去しました。
> Rancher2セットアップ: dockerダウングレード処理の除去

- publicscript/gitlab/gitlab.sh
- publicscript/magento/magento.sh
- publicscript/shirasagi/shirasagi.sh
- Git Lab
- 推奨コア 2コア以上
- 推奨メモリ 8GB以上
- SHIRASAGI
- 推奨コア 2コア以上
- 推奨メモリ 3GB以上
- Magento
- 推奨コア 4コア以上
- 推奨メモリ 8GB以上
> サーバの推奨スペックをタグとして付与するようにコメントを修正

- publicscript/mastodon/mastodon.sh
[最新のインストール方法](https://source.joinmastodon.org/mastodon/docs/blob/3411eb94d3c3b9225e1ca47f1b67969be7144f6a/content/en/administration/installation.md#L191)に合わせました。
また、現時点の Mastodon の .ruby-version では Ruby 2.6.1 がインストールされますが、[こちらの問題](https://bugs.ruby-lang.org/issues/15582)が存在するので、その解決のためにも必要となります。
> mastodon.sh で gem update --system を実行するように変更

- publicscript/redmine/redmine.sh
OptionParser::InvalidOption 回避のため。
> --no-rdoc --no-ri を --no-document で置き換え

- publicscript/vuls/vuls.sh
GO111MODULE=on への対応のため Go のバージョンを更新しました。
本スクリプトを使用し、問題なく実行できることを検証済みです。
> vuls の GOVERSION を 1.12.9 に変更

- publicscript/mattermost/mattermost.sh
mattermost を latest の 5.15.0 にバージョンアップしました。
実際にこのスタートアップスクリプトを実行し、動作に問題がないことを確認済みです。
> mattermost を 5.15.0 にバージョンアップ

- publicscript/mattermost/mattermost.sh
- publicscript/mattermost/mattermost_spec.rb
以下の変更を行ったのち、実際にスタートアップスクリプトを実行し、正常に動作することを確認しました。
また、rspec もすべてグリーンとなることを確認しています。
* [こちら](https://github.com/mattermost/docs/blob/92fa22e75fd8a20fd8cf2929a7abeb1ebc70de6b/source/administration/command-line-tools.rst#mattermost-36-and-later)の注に基づき `platform` ではなく `mattermost` コマンドを実行するように変更しました。
* [こちら](https://github.com/mattermost/docs/blob/92fa22e75fd8a20fd8cf2929a7abeb1ebc70de6b/source/install/install-rhel-7-mattermost.rst)の内容に基づき `/etc/systemd/system/mattermost.service` のいくつかの項目を更新しました。
> mattermost のコマンド名を platform から mattermost に修正

- publicscript/kibana/kibana.sh
実際に本スクリプトを実行し、挙動に問題がないことを確認済みです。
> 依存する gem の Ruby のバージョン指定に対応するため install-redhat-td-agent2.5.sh に変更

- publicscript/ruby_on_rails/ruby_on_rails.sh
ruby_on_rails.sh に以下の修正をしました。
* デフォルトの Ruby のバージョンを 2.3.0 から 2.6.5 に更新しました。
* CentOS 7 でも動作を確認済みとしました。
* https://github.com/rbenv/ruby-build/wiki#suggested-build-environment を参考に yum でインストールするパッケージの見直しを行いました。
CentOS 6 と CentOS 7 で本スクリプトに問題がないことを確認済みです。
> ruby_on_rails.sh の Ruby のバージョンを更新

- publicscript/node-red/node-red.sh
`${UI_PORT:=1880}` という定義の場合、
「変数に代入の上、その変数をコマンドとして実行する」という挙動になっていたため、
コマンドとして実行することがないように修正しました。
> node-red.sh の Node.js を 12.x 系に更新

- publicscript/lamp/lamp.sh
コンパネ側でシンプルモードのロゴ表示に用いるタグ( `@logo-alphabet-l` )を追加しました
> LAMPにシンプルモードに表示するロゴのタグ指定を追加

- README.md
- publicscript/jupyter_notebook/jupyter_notebook.sh
- publicscript/ruby_on_rails/ruby_on_rails.sh
- publicscript/terraform_for_sacloud/terraform_for_sacloud.sh
- publicscript/usacloud/usacloud.sh
- publicscript/xrdp/xrdp.sh
- publicscript/yum_update/yum_update.sh
以下を CentOS 8 に対応
* yum_update.sh
* terraform_for_sacloud.sh
* usacloud.sh
* xrdp.sh
* jupyter_notebook.sh
* ruby_on_rails.sh
> CentOS 8 対応の追加

- publicscript/jitsi_meet/jitsi_meet.sh
既存のJitsi MeetスタートアップスクリプトをUbuntu20.04に対応するよう修正しました。
修正には [Jitsi Meetのクイックスタートガイド](https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart) を参考しました。
serverspecによる自動テストと、PC間での会議の動作に問題ないことを確認済みです。
> Jitsi MeetスタートアップスクリプトのUbuntu20.04サポート

- publicscript/usacloud/usacloud.sh
Usacloud のv1.0系へのメジャーバージョンアップに伴いいくつかの修正を行いました。
- インストールスクリプトのダウンロード元を`releases.usacloud.jp`からGitHub Releasesへ変更
- `usacloud config`でのAPIキー/ゾーン設定を1コマンドで行うように変更
- `usacloud config`でデフォルト出力形式(`--default-output-type`)の追加
=> 上記2つはv1.0以降`usacloud config`コマンドに未指定のパラメータがあった場合に入力待ちが発生するようになったことへの対応
- bash-completionの有効化
=> v1.0以降Usacloudのインストールスクリプト内でbash-completionの有効化処理が行われなくなったため
> Usacloud を v1.0系 にアップデート

- publicscript/mailsystem/setup_scripts/_13_roundcube.sh
less 4.0.0 で問題が発生したため、バージョン 3.13.1 を指定してインストールするように変更
roundcube のバージョン指定方法の変更
> roundcubeのインストールスクリプトを修正

- publicscript/rancher2_setup/rancher2_setup.sh
Rancher2の最新版が動作するようにスタートスクリプトを修正しました。
`serverspec` のテストが通ることと、Rancher2上でWordPressをデプロイしてページが表示できる事を確認しました。
参考にしたURL：
推奨動作環境について
https://rancher.com/docs/rancher/v2.x/en/installation/requirements/#cpu-and-memory
`--privileged` オプションについて
https://rancher.com/docs/rancher/v2.x/en/installation/other-installation-methods/single-node-docker/
Rancher2上のクラスタ設定について
https://febc-yamamoto.hatenablog.jp/entry/sakura-rancher-startup-script
> Rancher2最新版が動作するように修正

- publicscript/rancher2_setup/rancher2_setup.sh
以下の更新を行っています。
- 選択可能なゾーンに東京第2ゾーン(tk1b)を追加
- 対象OSにCentOS8.XとCentOS8Streamを追加
- docker-ceをdocker.comから追加したリポジトリを使用してインストールするように修正
> Rancher2セットアップの更新

- publicscript/docker_for_ubuntu/docker_for_ubuntu.sh
- publicscript/docker_for_ubuntu/docker_for_ubuntu_spec.rb
* Ubuntu（2021/05/26現在でリリースされている 18.01-5,20.04）にて、Dockerの安定版をインストールするスクリプト
* 対象のアーカイブにて当該スタートアップスクリプトを指定し、`/root/.sacloud-api/notes/スタートアップスクリプトID.log` のステータスコードが `0` であること
* docker_for_ubuntu_spec.rb を `serverspec-init` 後、 `./spec/localhost/docker_for_ubuntu_spec.rb` として配置し、`sudo rake spec` を実行し、 `0 failures` であることを確認
> Docker for ubuntu

- publicscript/jitsi_meet/jitsi_meet.sh
Jitsi Meet スタートアップスクリプトが Ubuntu 18.04 でインストールに失敗する問題の修正を行います。
さくらのクラウド上の Ubuntu Server に修正後のスタートアップスクリプトを実行後、
serverspec にパスすることと Jitsi Meet ページを開いてビデオ通話が可能なことを確認しました。
Ubuntu Server 18.04 と 20.04 の両方で検証済みです。
> Jitsi MeetスクリプトがUbuntu 18.04 でインストールに失敗する問題の修正

- publicscript/siteguardlite/siteguardlite.sh
SiteGuard を5.00 Update 1  にアップデートしました。
また、今回から動作対象の OS（ディストリビューション）に AlmaLinux を追加しました。
ご確認よろしくお願いいたします。
追記：
スクリプト名から「for CentOS」の表記を削除しました。
さくらのクラウド上でスクリプトを実行して、問題なく動作することを確認しました。
- Centos
- AlmaLinux
で動作確認済みです。
<details>
<summary>Centos</summary>
</details>
<details>
<summary>AlmaLinux</summary>
</details>
> SiteGuard を 5.00 Update 1 に更新
