sakura-internet/cloud-startupscripts

publicscript/mastodon.sh

certbot-autoのcron設定の不具合修正
セットアップ完了後、サーバをrebootする処理を追加

mastodonのスタートアップスクリプトの更新

---

.editorconfig

ユーザ間でインデントや改行コード等の差異が発生しないように、 `.editorconfig` を取り入れてみました 🙏

.editorconfigの追加

---

publicscript/mattermost.sh

mattermostのバージョンを 3.10.0 から 4.0.1 に変更
mysqlの全文検索エンジンを ngram から mroonga に変更(検索速度向上、１文字から検索可能)
ゾーンとドメインが同じ場合でもセットアップ出来るように変更
DNS逆引きの登録の処理を修正
コメントの一部修正

Mattermost update 20170723

---

README.md

README.md に Mattermost のリンクを追加しました。

Mattermostのリンクを追加

---

publicscript/mastodon.sh

Mastodon v1.5.x系のインストールに必要なパッケージの追加(libidn-devel,libicu-devel)

Mastodon v1.5.x系のインストールに必要なパッケージの追加(libidn-devel,libicu-devel)

---

publicscript/mastodon.sh

/etc/motd に startup_script の進捗を表示、それに伴い /tmp/startup_script.log を廃止
Mastodon v1.5 で必要のなくなった /etc/cron.d/mastodon を廃止
certbot-auto で 使用するプラグインを standalone から webroot に変更
certbot-auto で webroot プラグインを使用するため、tcp/80 の設定追加
/home/mastodon/live/.env.production に VAPID_PRIVATE_KEY,VAPID_PUBLIC_KEY を設定

mastodon update

---

publicscript/node-red.sh

- nodesource リポジトリを追加
- nodesをインストールするリポジトリをepel から、nodesourceに変更
- yum update 追加
- エラー終了のコードを追加
- デバッグしやすいようにecho追加

nodejs install error fix

---

README.md
publicscript/gitlab.sh

- メモリの補足を追加
- フラグを `-e`  に変更し、エラー時は停止する

GitLab CE 細部の調整

---

publicscript/mailsystem/config.source
publicscript/mailsystem/mailsystem.sh
publicscript/mailsystem/script/backup_ldif.sh
publicscript/mailsystem/script/ldap_authentication.php
publicscript/mailsystem/script/remove_hold_queue.sh
publicscript/mailsystem/setup_scripts/_create_admin_address.sh
publicscript/mailsystem/setup_scripts/_create_mailaddress.sh
publicscript/mailsystem/setup_scripts/_setup_check.sh
publicscript/mailsystem/setup_scripts/_setup_clamd.sh
publicscript/mailsystem/setup_scripts/_setup_dns.sh
publicscript/mailsystem/setup_scripts/_setup_dns_ptr.sh
publicscript/mailsystem/setup_scripts/_setup_dovecot.sh
publicscript/mailsystem/setup_scripts/_setup_mariadb.sh
publicscript/mailsystem/setup_scripts/_setup_nginx.sh
publicscript/mailsystem/setup_scripts/_setup_opendkim.sh
publicscript/mailsystem/setup_scripts/_setup_openldap.sh
publicscript/mailsystem/setup_scripts/_setup_phpldapadmin.sh
publicscript/mailsystem/setup_scripts/_setup_postfix.sh
publicscript/mailsystem/setup_scripts/_setup_rainloop.sh
publicscript/mailsystem/setup_scripts/_setup_roundcube.sh
publicscript/mailsystem/setup_scripts/_setup_ssl.sh
publicscript/mailsystem/setup_scripts/_setup_thunderbird.sh
publicscript/mailsystem/setup_scripts/_setup_yenma.sh
publicscript/mailsystem/setup_scripts/_startup_function.lib
publicscript/mailsystem/templates/config-v1.1.xml.PLAIN
publicscript/mailsystem/templates/config-v1.1.xml.SSL
publicscript/mailsystem/templates/config.inc.php.password
publicscript/mailsystem/templates/config.inc.php.roundcube
publicscript/mailsystem/templates/nginx.conf

アプリケーション構成は下記ページに記述
http://qiita.com/ma3ki/items/cf1c4507eb8ab78e7c68
mailsystem.sh で cloudm-startupscripts を git clone してから、サブスクリプトを呼び出すため、
masterにマージされてからでないと動作しません

スターンドアローン構成でメールシステムをセットアップするスタートアップスクリプト

---

README.md

- README.md から、メールシステムのドキュメントへリンクを追加

「メールシステム」のドキュメントへのリンク追加

---

publicscript/mailsystem/setup_scripts/_setup_rainloop.sh

初回アクセス時にapplication.iniが生成されなくなり、インストールが失敗していた問題の対応

Rainloopのバージョンアップ対応

---

publicscript/mastodon/mastodon.sh

スタートアップスクリプトの文字数が10000文字を超える為、postfixの設定を１つ削除

Rubyのインストールバージョンを .ruby-version から取得するように変更

---

README.md

Laravelの説明をREADME.mdに追加

---

publicscript/mattermost/mattermost.sh

エラーハンドリング処理の追加
Mattermostのバージョンを4.3.0に変更

specファイルでテストできるように修正など

---

publicscript/laravel/laravel.sh

Laravel のバージョンを 5.5 に変更
PHPのバージョンを 7 に変更
エラー処理の変更

Laravel のバージョンを 5.5 に変更

---

publicscript/terraform_for_sacloud/terraform_for_sacloud.sh

Terraform for さくらのクラウド v1.0.0からリリースファイル名が変更となります。
同時にリリースファイル(zip)に対するsha256sumでのチェックサムも公開されるようになります。
これらの対応としてこのPRでは以下の対応を行います。
- GitHubのタグからTerraform for さくらのクラウドの最新リリースタグを取得
- 取得したタグからダウンロードするファイル名を決定
- ダウンロードしたファイルに対しチェックサム確認
また、curlコマンドのオプション指定部分を合わせて簡素化しています。

Terraform for さくらのクラウド リリースファイル名変更

---

publicscript/node-red/node-red.sh

Node-RED ログイン機能追加

---

publicscript/node-red/node-red.sh

ログイン IDとパスワードを入力した場合、Node-REDのログイン画面が有効になるように処理を修正
motd にスタートアップスクリプトの進行状況を出力する処理を追加
node-red の起動オプションから -v を削除

Node-REDのログイン画面処理の修正

---

publicscript/node-red/node-red.sh

Node-REDのUIにて、スペースを含むパスワードが利用できない問題を修正しました

Node-REDにて、スペースを含むパスワードが利用できない問題を修正

---

publicscript/basercms/basercms.sh

初期適用テーマを、bc_sample に変更して、スクリプトの説明文を調整しました。
よかったらマージお願いします。

スクリプトの説明文と初期適用テーマを変更

---

publicscript/vuls/vuls.sh

Vuls v4.0.0よりOVALを使用するよう変更になっているためスクリプトに追加しました。
https://github.com/future-architect/vuls/releases

vulsにgoval-dictionaryを追加

---

publicscript/wordpress_for_centos7/wordpress_for_centos7.sh
publicscript/wordpress_for_centos7/wordpress_for_centos7_spec.rb

CentOS 7対応のWordPressスタートアップスクリプトを作りました。

WordPress for CentOS 7を追加

---

publicscript/shirasagi/shirasagi.sh

nginxのパッケージをnginx.orgから入手するように変更

change shirasagi.sh

---

publicscript/mailsystem/setup_scripts/_setup_check.sh
publicscript/mailsystem/setup_scripts/_setup_clamd.sh
publicscript/mailsystem/setup_scripts/_setup_nginx.sh
publicscript/mailsystem/setup_scripts/_setup_postfix.sh
publicscript/mailsystem/setup_scripts/_setup_roundcube.sh
publicscript/mailsystem/setup_scripts/_setup_ssl.sh

postfix の starttls の設定を変更
roundcube のインストールバージョンを変更

clamav-milter のインストール方法を修正

---

publicscript/mailsystem/setup_scripts/_setup_clamd.sh

clamdのセットアップが失敗する問題の修正をしました。

---

README.md
publicscript/git_clone/git_clone.sh
publicscript/gitlab/gitlab.sh
publicscript/jupyter_notebook/jupyter_notebook.sh
publicscript/kibana/kibana.sh
publicscript/rabbitmq/rabbitmq.sh
publicscript/redmine/redmine.sh
publicscript/ruby_on_rails/ruby_on_rails.sh
publicscript/vuls/vuls.sh
publicscript/wordpress/wordpress.sh

`@sacloud-require-archive` の付与が漏れているものを修正しました 🙏

@sacloud-require-archiveを追加

---

publicscript/redmine/redmine.sh

via https://github.com/rvm/rvm-site/blob/e88911415e172da68f7a39fae84fe39b5cdbed8c/content/rvm/security.md#install-our-keys

redmine の rvm のインストール方法を更新

---

publicscript/redmine/redmine.sh

via https://github.com/rvm/rvm-site/blob/70c932d6357f3c88199bb629ffc5d6fdea4c742d/content/rvm/security.md

hkp://keys.gnupg.net から hkp://pool.sks-keyservers.net に変更

---

README.md
publicscript/drupal_for_centos7/drupal_for_centos7.sh
publicscript/drupal_for_ubuntu/drupal_for_ubuntu.sh
publicscript/magento/magento.sh

実際にさくらのクラウド上でスタートアップスクリプトを実行し、問題ないことを確認済み。

Drupal と Magento の Ubuntu のバージョンを更新

---

publicscript/nextcloud/nextcloud.sh

/var/www/html/nextcloud 配下の .htaccess が有効となるように設定を追加します

nextcloud.sh apacheの設定を出力するように

---

README.md
publicscript/letsencrypt/letsencrypt.sh

ワイルドカード証明書を取得するように変更
CAAレコードの登録機能を追加

DNS認証で証明書を発行するように変更

---

publicscript/mailsystem/setup_scripts/_04_rspamd.sh

https://rspamd.com/doc/configuration/index.html#rspamd-basic-configuration

mailsystem: Fix rspamd options filename typo

---

publicscript/owncloud/owncloud.sh

owncloud.sh の リポジトリURL を修正

---

publicscript/boltzengine/boltzengine_spec.rb

boltzengine_spec.rb 追加

---

README.md
publicscript/docker_for_centos7/docker_for_centos7.sh
publicscript/docker_for_centos7/docker_for_centos7_spec.rb

CentOS 7 で Docker CE をセットアップするための、スタートアップスクリプトです。

Docker CE for CentOS 7 の追加

---

README.md
publicscript/gitlab/gitlab.sh

GitLab CE -> GitLab Core への差し替えです。

GitLab Coreのスタートアップスクリプトを追加

---

publicscript/mastodon/mastodon.sh

usacloudでDNSレコード登録をするように変更
下記の問題にセットアップに失敗していた為、問題を回避するコードを追加
https://github.com/tootsuite/mastodon/pull/13294

Mastodon のスタートアップスクリプトの修正

---

publicscript/mastodon/mastodon.sh
publicscript/restyaboard/restyaboard.sh

mastodon, restyaboard が参照している リポジトリのURLの更新

---

publicscript/jupyterlab/jupyterlab.sh

yum update 前に yum clean all を追加しました。

yum update 前に yum clean all の追加

---

publicscript/siteguardlite/siteguardlite.sh

SiteGuard をVer4.10 Update1 にアップデートいたしました。
マイナーアップデートでしたので、スクリプトの修正はファイルのバージョンを変更した程度です。
※ 動作確認済み

SiteGuard をVer4.10 Update1 にアップデート

---

publicscript/netbox/netbox.sh
publicscript/netbox/netbox_spec.rb

さくらのクラウド向けに NetBox のスタートアップスクリプトを作成しました。
スクリプト作成には [NetBox のドキュメント](https://netbox.readthedocs.io/en/stable/installation/) を参考しました。
今回は、Ubuntu 20.04 のみの対応となります。
※ 動作確認済み
お手すきの際にご確認よろしくお願いいたします。

NetBox のスタートアップスクリプトを追加

---

publicscript/jitsi_meet/jitsi_meet.sh

スクリプトが正常に動作しないため幅ゼロスペースを削除します。

JitsiMeetスクリプトに混入した幅ゼロスペースを削除

---

publicscript/zabbix-agent/zabbix-agent.sh
publicscript/zabbix-server/zabbix-server.sh

対象のOSをCentOS7からCentOS8に変更
インストールするZabbixのバージョンを 5.0系 に変更

zabbix-agent, zabbix-server のスタートアップスクリプトを更新

---

publicscript/ipsetting_for_centos/ipsetting_for_centos.sh
publicscript/ipsetting_for_centos/ipsetting_for_centos_spec.rb

gpg認証を行いました。再PRです。
よろしくお願いします。

CentOS IPアドレス設定スクリプト
